# From: https://github.com/mamba-org/mamba/blob/7a4f488568d71335f807b280719c2a03f39651ff/.github/workflows/test_micro.mamba.pm.yml

name: Test micro.mamba.pm

on:
  # schedule:
  #   - cron: '0 10 * * *'
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_micro_mamba_pm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, shell: bash, shell-source-param: -i}
          # - {os: macos-latest, shell: zsh, shell-source-param: -i}
          # - {os: macos-latest, shell: bash, shell-source-param: -l}
          # - {os: windows-latest, shell: bash, shell-source-param: -l}
    steps:
      - name: Install Micromamba (${{ matrix.os }}, ${{ matrix.shell }})
        run: |
          # TODO: Update install.sh script for Windows
          if [ ${{ matrix.os }} = windows-latest ]; then
            mkdir -p ~/bin
            curl -Ls https://micro.mamba.pm/api/micromamba/win-64/latest \
              | bunzip2 | tar xOf - Library/bin/micromamba.exe > ~/bin/micromamba.exe
          else
            curl http://micro.mamba.pm/install.sh | ${{ matrix.shell }}
          fi
      - name: Test micromamba
        run: | 
          which micromamba
          micromamba
      - name: Debug point
        uses: mxschmitt/action-tmate@v3
        if: always()
      - name: Remove micromamba from PATH
        run: |
          export PATH=${PATH/':/home/runner/.local/bin'/}
          ${{ matrix.shell }} ${{ matrix.shell-source-param }} -ec "type micromamba"
          ${{ matrix.shell }} ${{ matrix.shell-source-param }} -ec micromamba
        if: always()
